// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRy79vx6RQYQn8zqQWNFf5DKtVmLcbU8',
    appId: '1:119070099611:web:25eabc08fcb8b030fdde3e',
    messagingSenderId: '119070099611',
    projectId: 'naber-55153',
    authDomain: 'naber-55153.firebaseapp.com',
    storageBucket: 'naber-55153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNi6SZinySQ_fs2u5TErYYGYRGUdqyHw',
    appId: '1:119070099611:android:72c57a1c97d5fda4fdde3e',
    messagingSenderId: '119070099611',
    projectId: 'naber-55153',
    storageBucket: 'naber-55153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYex0AyOtEnOBZM8H5vdrEIhHRNa9NZ8',
    appId: '1:119070099611:ios:c805ae60c2016739fdde3e',
    messagingSenderId: '119070099611',
    projectId: 'naber-55153',
    storageBucket: 'naber-55153.firebasestorage.app',
    iosBundleId: 'com.example.naber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRYex0AyOtEnOBZM8H5vdrEIhHRNa9NZ8',
    appId: '1:119070099611:ios:c805ae60c2016739fdde3e',
    messagingSenderId: '119070099611',
    projectId: 'naber-55153',
    storageBucket: 'naber-55153.firebasestorage.app',
    iosBundleId: 'com.example.naber',
  );
}
